apiVersion: databases.schemahero.io/v1alpha4
kind: Database
metadata:
  name: mabecenter-db
  namespace: schemahero-changelog
spec:
  connection:
    postgres:
      uri:
        valueFrom:
          secretKeyRef:
            name: schemahero-database-secret
            key: uri