apiVersion: databases.schemahero.io/v1alpha4
kind: Database
metadata:
  name: changelog
  namespace: schemahero-changelog
spec:
  immediateDeploy: true
  connection:
    postgres:
      uri:
        valueFrom:
          secretKeyRef:
            name: schemahero-database-secret
            key: uri