apiVersion: databases.schemahero.io/v1alpha4
kind: Database
metadata:
  name: postgres
  namespace: schemahero-changelog
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  connection:
    postgres:
      uri:
        valueFrom:
          secretKeyRef:
            name: schemahero-database-secret
            key: uri