
apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: videos
  namespace: schemahero-changelog
spec:
  database: changelog
  name: videos
  schema:
    postgres:
      primaryKey:
      - id
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: title
        type: text
        constraints:
          notNull: true