schemahero:
  service:
    port: 443

  image:
    name: schemahero/schemahero-manager
    # Will use .Chart.AppVersion by default
    tag: ""
    # Defaults to Docker Hub
    registry: ""

  extraArgs: []

  # name-value pairs, see https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
  extraEnv: []

  # See https://kubernetes.io/docs/concepts/configuration/manage-resources-containers
  resources:
    limits:
      cpu: "1"
      memory: 150Mi
    requests:
      cpu: 100m
      memory: 50Mi

  # See https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}
    # nodeAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     nodeSelectorTerms:
    #       - matchExpressions:
    #           - key: kubernetes.io/os
    #             operator: In
    #             values:
    #               - linux
    #           - key: kubernetes.io/arch
    #             operator: In
    #             values:
    #               - amd64