apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: schemahero-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.company.com/infra-repo.git
    targetRevision: main
    path: charts/schemahero-sierra-group
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
