apiVersion: schemas.schemahero.io/v1alpha4
kind: Function
metadata:
  name: hello-world
  namespace: schemahero-changelog
spec:
  database: postgres
  name: hello_world
  schema:
    postgres:
      schema: company
      lang: PLpgSQL
      as: |-
        SELECT 'Hello, world!'::text;
      params: []   
