apiVersion: schemas.schemahero.io/v1alpha4
kind: Function
metadata:
  name: hello-world
  namespace: schemahero-changelog
spec:
  # Nombre del Database CR al que apunta
  database: changelog

  # Nombre interno de la función en PostgreSQL
  name: hello_world

  # Si se elimina el CR, la función se borrará de la base de datos
  removeOnDeletion: true

  schema:
    postgres:
      # Esquema dentro de la BD donde se creará la función
      schema: public

      # Lenguaje de la función: PLpgSQL o SQL
      lang: PLpgSQL

      # Definición del cuerpo de la función
      as: |-
        BEGIN
          RETURN UPPER(input_text);
        END;

      # Parámetros de entrada/salida
      params:
        - name: input_text
          type: text
          mode: IN

      # Tipo de retorno
      return: text

      # ¿Devuelve un SET de filas?
      returnSet: false
