apiVersion: schemas.schemahero.io/v1alpha4
kind: Function
metadata:
  name: hello-world
  namespace: schemahero-changelog
spec:
  database: postgres
  removeOnDeletion: true
  postgres:
    schema: company
    lang: SQL
    params: []            # sin parámetros
    return: text
    as: |
      SELECT 'Hello, world!'::text;
