apiVersion: schemas.schemahero.io/v1alpha4
kind: Function
metadata:
  name: users
  namespace: schemahero-changelog
spec:
  database: changelog
  name: get_user_count
  immediateDeploy: true
  schema:
    postgres:
      schema: public
      lang: PLpgSQL
      return: bigint
      as: |-
        DECLARE
            user_count bigint;
        BEGIN
            SELECT COUNT(*) INTO user_count FROM users;
            RETURN user_count;
        END;