apiVersion: schemas.schemahero.io/v1alpha4
kind: Function
metadata:
  name: hello-world
spec:
  database: mabecenter-db
  immediateDeploy: true
  name: hello_world
  schema:
    postgres:
      schema: company
      lang: PLpgSQL
      as: |-
        SELECT 'Hello, world!'::text;
      params: []   
