apiVersion: schemas.schemahero.io/v1alpha4
kind: Function
metadata:
  name: users
spec:
  database: changelog
  name: get_user_count_2
  schema:
    postgres:
      schema: config
      lang: PLpgSQL
      return: bigint
      as: |-
        DECLARE
            user_count bigint;
        BEGIN
            SELECT COUNT(*) INTO user_count FROM users LIMIT 1;
            RETURN user_count;
        END;