
apiVersion: schemas.schemahero.io/v1alpha4
kind: Function
metadata:
  name: testing
spec:
  database: changelog
  name: testing
  schema:
    postgres:
      # Esquema dentro de la BD donde se creará la función
      schema: public

      # Lenguaje de la función: PLpgSQL o SQL
      lang: PLpgSQL

      # Definición del cuerpo de la función
      as: |-
        BEGIN
          RETURN UPPER(input_text);
        END;

      # Parámetros de entrada/salida
      params:
        - name: input_text
          type: text
          mode: IN

      # Tipo de retorno
      return: text

      # ¿Devuelve un SET de filas?
      returnSet: false
