apiVersion: functions.schemahero.io/v1alpha4
kind: Function
metadata:
  name: changelog-hello-world
spec:
  database: changelog
  name: hello_world
  schema:
    postgres:
      lang: SQL
      as: |-
        SELECT 'Hello, world!'::text;
      params: []   
